;;;; dbmapper.lisp

(in-package #:dbmapper)






;; Find joins between two tables
;; -----------------------------


;; hashing utilities

;; convert arbitrary string to integer

(defun hash-string (input)
  (sxhash input))

;; combine individual hashes (multiply element hashes together mod some high prime, use fold)

(defun hash-integer-list (input)
  (reduce (lambda (total int) (mod (* (mod int 104729) total) 104729)) input))



;; convert column to hash-table with key-value generated by hashing function (so every hash is unique)
(defun hash-column (col)
  (map 'list #'hash-string (remove-duplicates col)))

;; compare two columns
;; want to check if columns contain the same value types
;; so we construct a "set" of values for each column and
;; see if they are equivalent
;; Assumption: columns do not contain symbols, as this would
;; break our hashing function

(defun same-column-p (hashed-list1 hashed-list2)
  (= hashed-list1 hashed-list2))
